- regExp: ".*\\.ts+$"
  labels: ["typescript"]
- regExp: ".*\\.sql+$"
  labels: ["database", "critical"]
- regExp: ".*/docs/"
  labels: ["documentation"]
- regExp: ".*\\.png+$"
  labels: ["images"]
- regExp: "^(pom\\.xml|package\\.json|build\\.gradle)$"
  labels: ["dependencies"]
- regExp: ".*/requirements.txt"
  labels: ["dependencies"]
- regExp: ".*\\.(zip|jar|war|ear)+$"
  labels: ["artifact", "invalid"]
- regExp: ".*/setup.py"
  labels: ["build"]
- regExp: "^.github/"
  labels: ["github-workflow"]
- regExp: "^nets/8r-1c-in-band-isis/"
  labels: ["topology/8r-1c-in-band-isis"]
- regExp: "^nets/8routers-isis-ipv6/"
  labels: ["topology/8routers-isis-ipv6"]
- regExp: "^nets-unmantained/8r-1c-out-band-isis/"
  labels: ["topology/8r-1c-out-band-isis"]
- regExp: "^nets/3routers/"
  labels: ["topology/3routers"]
- regExp: "^nets/8routers/"
  labels: ["topology/8routers"]
- regExp: "^nets-in-progress/8r-1c-srv6-pm/"
  labels: ["topology/8r-1c-srv6-pm"]
- regExp: ".*/.env"
  labels: ["configuration"]
